version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/localubi
    depends_on:
      - db
    volumes:
      - ./.env.local:/app/.env.local

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=localubi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
